### ISSUE TITLE
xelatex support

### ISSUE THREAD

**Issue by oatmealm** [doc-org/doc-org#1]
Hi! What a great idea. Looking to try it ASAP. 

I'm not versed with latex but did try couple of times to work with it to produce mixed script documents, mainly English-Arabic-Hebrew and know it's not trivial. 

Given you're using latexmk if I'm not mistaken, how would I go about preparing documents?

I'd need to prepare a correct latex header and setup main.org language properties etc., but does the docker image include xelatex, or would I need to create my own based off your image? Where do I keep the latexmk config file, etc. 

Thanks

**Comment by marcoieni** [comment]
> does the docker image include xelatex

Hi, there is no magic. [This](https://github.com/doc-org/docker/blob/master/Dockerfile) is the dockerfile.
If something is missing you can create your own dockerfile. If you think that it is something that will be useful to most of the people you can create a pull request.

I quote from [this](https://www.quora.com/How-does-one-add-something-new-to-an-already-existing-docker-image/answer/Shahin-Ershad):

> Create a Dockerfile which uses the existing image as base image and add the required installation packages or modules you want inside the image using RUN command
Dockerfile should be somewhat like this :
`FROM <existing image name>`
`RUN apt-get update && pip install tensorflow`
Then again build the new image using the command:
`docker build -t <image-name>:<tag>`

> how would I go about preparing documents?

You can find examples [here](https://github.com/doc-org/examples)

> Where do I keep the latexmk config file

[this](https://mg.readthedocs.io/latexmk.html#local-configuration-files) page says that you can keep it in the current directory. I haven't tried, but you can try to place it together with the documents. Again, there is no magic and the [script](https://github.com/doc-org/docker/blob/master/src/run.sh) is really simple. Happy hacking! :)
